version: '3.7'
services:
  postgres: 
    image: bitnami/postgresql:latest
    ports: 
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=tome
      
    volumes:
      - tome_postgres_data:/bitnami/postgresql
    
  redis:
    image: bitnami/redis:latest
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - tome_redis_data:/bitnami/redis
    
volumes:
  tome_postgres_data:
  tome_redis_data: